const mongoose = require("mongoose");

const NfoSchema = new mongoose.Schema({
  title: { type: String },
  originaltitle: { type: String },
  sorttitle: { type: String },
  epbookmark: { type: String },
  year: { type: String },
  ratings: [{ type: Object }],
  userrating: { type: String },
  top250: { type: String },
  set: { type: String },
  plot: { type: String },
  outline: { type: String },
  tagline: { type: String },
  runtime: { type: String },
  thumb: [{ type: Object }],
  fanart: [{ type: Object }],
  mpaa: { type: String },
  certification: { type: String },
  id: { type: String },
  tmdbid: { type: String },
  uniqueid: [{ type: Object }],
  country: { type: String },
  status: { type: String },
  code: { type: String },
  premiered: { type: String },
  watched: { type: Boolean },
  playcount: { type: Number },
  lastplayed: { type: String },
  genre: [{ type: String }],
  studio: [{ type: String }],
  credits: [{ type: Object }],
  director: [{ type: Object }],
  tag: [{ type: String }],
  actor: [{ type: Object }],
  producer: [{ type: Object }],
  trailer: [{ type: String }],
  languages: [{ type: String }],
  dateadded: { type: Date },
  fileinfo: [{ type: Object }],
  source: { type: String },
  edition: { type: String },
  original_filename: { type: String },
  user_note: { type: String },
});

module.exports = mongoose.model("Nfo", NfoSchema);
